### ISSUE TITLE
Incorrect Typing of parameter in "onSelection"

### ISSUE THREAD

**Issue by MartinHaeusler** [scniro/react-codemirror2#30]
According to the type information provided by `react-codemirror2`, the `onSelection` callback is defined as follows:

` onSelection?: (editor: IInstance, ranges: ISetSelectionOptions) => void;`

... where `ISetSelectionOptions` is defined as: 

    export interface ISetSelectionOptions {
        anchor: codemirror.Position;
        head: codemirror.Position;
    }

However, when the listener is actually fired during runtime, the object I receive as the `ranges` parameter does not match the type outlined above. It is:

![image](https://user-images.githubusercontent.com/16356998/32186854-925febbe-bda3-11e7-885a-39766e078f69.png)

It's an object with a property `ranges`, which in turn is an array of `ISetSelectionOptions`.

I am using:
 - `react-codemirror2`: 3.0.3
 - `codemirror`: 5.31.0

**Comment by scniro** [comment]
This should now be fixed with the [3.0.7 release](https://github.com/scniro/react-codemirror2/releases/tag/3.0.7). I've added this my list of issues to take up with [@types/codemirror](https://www.npmjs.com/package/@types/codemirror) as there are quite a few incorrect signatures that I've need to hack my way around. E.g. this is what I have to work with from them...

    on(doc: Doc, 
       eventName: 'beforeSelectionChange', 
       handler: (instance: CodeMirror.Editor, 
       selection: { head: Position; anchor: Position; }) => void ): void;

yet, and as you found out, [codemirror actually returns something different](https://codemirror.net/doc/manual.html#event_beforeSelectionChange)...

    "beforeSelectionChange" (instance: CodeMirror, obj: {ranges, origin, update})

Workaround is in place for now though

**Comment by scniro** [comment]
Closing for now, please re-open should this remain problematic
