### ISSUE TITLE
Update the props to better reflect the Codemirror APIs

### ISSUE THREAD

**Issue by marcofugaro** [scniro/react-codemirror2#8]
This was the only confusing the first time I switched to this repo, basically I didn't understand why `onChange` didn't work, then I went to read the docs here and updated it.

I think `onChange` follows better the apis described here http://codemirror.net/doc/manual.html

Also I need to use the `beforeChange` event, and looking at the source code it seems you didn't expose it to the component. Is that right?

All the other things did work fine, great job with this repo!

**Comment by scniro** [comment]
@marcofugaro I totally agree and have been thinking on exactly this for a bit now. Thanks for opening this up. I'll be sure to post an update here when the changes are made!

**Comment by scniro** [comment]
This should now be fixed with the 1.0.0 release. The APIs are now `onSet` and `onChange`. Please check out the [README ](https://github.com/scniro/react-codemirror2/blob/master/README.md)on the notes for the optional `onBeforeSet` and `onBeforeChange` callbacks now available. Please let me know if this is what you were expecting!

**Comment by marcofugaro** [comment]
Hey that was quick! Good job!

Yes, I need to implement disabled lines in the editor, your `onBeforeChange` implementation will work nice! I'll try it and let you know if I find more issues.

Closing for now.

**Comment by scniro** [comment]
👍 please let me know should you have any further troubles!
