### ISSUE TITLE
CodeMirror.defineMode is not a function with Webpack

### ISSUE THREAD

**Issue by shawnatxapp** [scniro/react-codemirror2#93]
Hi.

I am attempting to add a mode to the Editor.

It is configured as such:

```
import CodeMirror from "codemirror";
import React, { PureComponent } from "react";
import { Controlled as CodeMirrorEditor, IInstance } from "react-codemirror2";
...
import "codemirror/lib/codemirror.css";
...
require("codemirror/mode/javascript/javascript");
```

and implemented like:

```
render() {
        const codeMirrorOpts = {
            lineNumbers: true,
            mode: "javascript"
        };

        return (
            <CodeMirrorEditor
                        value={mutableLogic.compiled}
                        onBeforeChange={this.handleEditorChange}
                        options={codeMirrorOpts} />
        );
    }
```

(Full gist [here](https://gist.github.com/shawnatxapp/6c21e253fcf46d38c959bc143503c718))

When the page loads, the following error is printed to the console: `TypeError: CodeMirror.defineMode is not a function`

Has anyone else had issues with setting this up with Webpack?

**Comment by scniro** [comment]
@shawnatxapp The [example](https://github.com/scniro/react-codemirror2/blob/master/docs/src/components/Editor.jsx#L101) for `defineMode` uses webpack just fine. Closing for now as this seems to be specific to your usage

**Comment by Manuelbaun** [comment]
Hi, 
I have the same issue. My imports:
```
import React, { Component } from 'react';
import { UnControlled as CodeMirror } from 'react-codemirror2'
// import CodeMirror from "react-codemirror";
import 'codemirror/lib/codemirror.css';
import 'codemirror/theme/material.css';
import 'codemirror/addon/mode/simple.js';

....
console.log(CodeMirror.defineSimpleMode) // already undefined
```

the `'codemirror/addon/mode/simple.js';` exists and defineSimpleMode should work, but it's not.

I am using react, my package.json:
```
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^1.2.3",
    "axios": "^0.18.0",
    "react": "^16.4.1",
    "react-codemirror2": "^5.1.0",
    "react-dom": "^16.4.1",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "codemirror": "^5.39.2",
    "react-codemirror": "^1.0.0"
  }
}

```

**Comment by shawnatxapp** [comment]
Haven't had much opportunity to look into it, but I think it likely has something to do with async loading or some form of lazy module resolution?

**Comment by JoshCheek** [comment]
I've discovered that if I change the mode's import line it works ([here](https://github.com/codemirror/CodeMirror/blob/74f31990f24ae03e214cf67c430ee2697abebe8c/mode/ruby/ruby.js#L6
))

```js
// currently it is this, which returns an empty object
if (typeof exports == "object" && typeof module == "object") // CommonJS
  mod(require("../../lib/codemirror"));

// it works when I change it to this
if (typeof exports == "object" && typeof module == "object") // CommonJS
  mod(require("codemirror"));
```

I assume this is due to my webpack config or my babel config, but don't know how to figure out why this behaviour is happening. I tried commenting out plugins that sounded like they might be related, tried messing with Babel's `presets["@babel/preset-env"].modules` (eg setting it to commonjs or amd), tried adding `create-react-app`'s named asset importer (I don't think I succeeded at this). Tried removing `exclude: [/node_modules/]` from the webpack rule for `babel-loader`.

**Comment by scniro** [comment]
@JoshCheek thanks for elaborating with some details. Given what you've provided I'm still not entirely sure what the issue would be as I've yet to experience it. Fortunately this project has a full blown [demo build](https://github.com/scniro/react-codemirror2/tree/master/docs) with webpack and all, perhaps you can compare the config to what you're running on your end? Something might jump out, just a thought!

**Comment by JoshCheek** [comment]
Will do. I also figured out that why it's coming back with an empty object: it's finding `codemirror.css` instead of `codemirror.js` Was able to figure this out by adding `console.log(require.resolve("../../lib/codemirror"))` to `node_modules/codemirror/mode/ruby/ruby.js` So somehow my webpack is not preferring the JS file. I'll compare with your examples, ty :)

**Comment by JoshCheek** [comment]
Found a presumably better solution, we reordered the list of extensions so that it looks at `js` files first.
